<div class="container-xxl py-5">
    <div class="container">
        <div class="row">
            <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
                <p class="d-inline-block border rounded-pill py-1 px-4">Blog</p>
            </div>
            <div class="container">
                <div class="col-lg-12 wow fadeIn" data-wow-delay="0.5s">
                    <div class="post-teaser">
                        <div class="align-items-center justify-content-center mx-auto d-block bg-white rounded-circle mb-4 h-50 w-50">
                            <img class="card-img-top rounded" src="img/Blog/infertilidade.png" alt="">
                        </div>
                        <h1 class="mb-3 text-center rounded-pill">Os impactos emocionais da infertilidade</h1>
                        <div class="post-teaser">
                            <p>Na história da humanidade, desde a bíblia e dos escritos mitológicos, a infertilidade já se fazia presente. A impossibilidade de gerar filhos tem sido tratada erroneamente ao longo dos tempos e nas mais diferentes culturas como algo vergonhoso, um castigo divino. A mulher infértil era rechaçada por seu entorno social e rotulada como incapaz, afinal, ter filhos era parte inerente à vida e representava uma obrigação para todo casal. Portanto, quem não tinha filhos se ver fora dos “padrões” sociais vigentes.</p>
                            <p>Os impactos emocionais provocados com o diagnóstico da infertilidade são semelhantes ao do luto. Afinal, o casal e/ou individuo perde a capacidade de procriar natural e espontaneamente, é necessário um tempo para se reorganizar psiquicamente, processar a informação, sentir esse luto até se sentir pronto para, se assim quiser, prosseguir com o processo do tratamento que se torna desgastante em todos os sentidos (físico, emocional e financeiro). </p>
                            <p>Gestar e procriar tem um efeito positivo e intenso no narcisismo, na autoestima, no fortalecimento de relações familiares e na expansão do vínculo conjugal. Porém, quando a decisão de ter filhos chega e esta não é acompanhada pela performance física que se espera, temos com a mesma intensidade o efeito negativo desse insucesso. Instala-se uma crise vital, e as reações emocionais são intensas e impactantes na saúde física e psíquica.</p>
                            <p>Uma vez que a infertilidade provoca uma profunda sensação de perda (ausência do filho idealizado vindo por meios naturais) e de impotência, todos os pacientes passam por um ciclo de adaptação emocional a essa nova realidade: primeiro é o choque da notícia, a descoberta da infertilidade causa uma espécie de paralisação onde a maioria prefere “dar um tempo” para ver se alguma coisa acontece naturalmente. Quando ainda sob o impacto emocional das informações recebidas, as pacientes tendem a olhar os médicos e os tratamentos em reprodução assistida como antídotos mágicos contra esse “mal” que recai sobre suas vidas e interrompe seus planos. A raiva, a revolta e a frustração facilmente podem ser projetadas no médico ou na equipe de saúde que assessora o tratamento reprodutivo.</p>
                            <p>As mulheres inférteis apresentam quase 25% a mais de sintomas depressivos quando comparadas com um grupo sem tal dificuldade. Os casais experimentam quase que inevitavelmente sentimentos profundos de inferioridade, vergonha e culpa. A sensação de inadequação e o desespero abrem espaço para o medo e a raiva. As reações mais comuns são: a sensação de serem incompletos sem o filho, a projeção da culpa em um dos parceiros, tornando a conversa sobre o tema um conflito ainda maior; a diminuição ou ausência do prazer sexual; o afastamento do convívio social.</p>
                            <p>A ferida narcísica que a infertilidade provoca pode facilmente se transformar em um luto silencioso, e os momentos de angústia e desespero geram mudanças na forma de o casal se relacionar entre si e com o mundo. Esse desequilíbrio emocional aumenta a incidência de transtornos psicossomáticos e a negação ou dificuldade para lidar com os tratamentos médicos.</p>
                            <p>Quando o casal passa por toda essa negação, raiva e tristeza, podem enfim começar a aceitar e encarar o problema em questão. Há uma reorganização da vida pessoal de forma a aliviar a ansiedade e conseguir um manejo consciente e seguro sobre os passos a serem seguidos para alcançar o filho desejado. Quando o casal não consegue oferecer um apoio mútuo, isto é, quando o impacto da infertilidade recai negativamente sobre o vínculo conjugal, observa-se uma sobrecarga no psiquismo feminino, e consequentemente os riscos de uma nova crise emocional aumentam. Por isso, quando falamos de infertilidade, independente se é fator feminino ou masculino, a infertilidade é do casal. Ou seja, é extremamente importante que vivam isso juntos e se apoiem. </p>
                            <p>Segundo pesquisas, mulheres com mais de quatro anos de tratamento da infertilidade e que recebiam atendimento psicológico foram comparadas com um grupo controle, de mulheres também inférteis que já estavam em tratamento da mesma forma, mas que não tinham acompanhamento psicológico oferecido pela instituição. Após 18 meses de acompanhamento, observou-se que as mulheres que receberam suporte psicoterápico conseguiram realizar o desejo de ser mãe em um número significativamente maior que as do grupo controle. A porcentagem de gestações ao final do tratamento foi de 54% para as que receberam a terapia em comparação com 20% das demais.</p>
                            <p>Algumas outras pesquisas ainda apontam que algo do desejo do médico ou dos técnicos tem sim o poder de influenciar o psiquismo dos futuros pais e favorecer os resultados do tratamento.<br>
                                A postura do médico deveria, portanto, compreender tanto o acolhimento dos conteúdos emocionais do casal quanto o rigor técnico e processual do tratamento, desde o primeiro contato até o desfecho da condução do caso, independentemente do resultado final. É importante manter durante todo o processo um clima de abertura, no qual aspectos técnicos e humanos do tratamento sejam abordados com transparência e empatia. Contar com uma equipe multidisciplinar pode ajudar muito no processo e fazer toda a diferença. </p>
                            <p>Marina Araújo<br>
                                Psicóloga Perinatal<br>
                                (CRP – 21/03665)</p>
                        </div>
                    </div>
                </div>
            </div>